#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100

b = 1

while (b <= 100));
do
    if ((b % 3 == 0 && b % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((b % 3 == 0))
    then
        echo "Fizz"
    elif ((b % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$b"
    fi
    ((b++))
done
