#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, then displays hi on the 9th iteration

b=0

while [ $b -lt 10 ] 
do
    echo "Best School";
    if [ $b -eq 8 ]
    then
       echo "Hi";
    fi
    ((b++))
done
