#!/usr/bin/env bash
# A bash script that displays bad luck, good luck for the 4th and 8th iterations respectively

b=0

while ((b < 10));
do
    if [ $b -eq 3 ]
    then
        echo "bad luck"
    elif [ $b -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((b++))
done
